// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvjfoajjzzbgzxelqood.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2amZvYWpqenpiZ3p4ZWxxb29kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODU0MDQsImV4cCI6MjA1OTg2MTQwNH0.snBlLtKu0Pve307OOT4qkZ9c0ij-P0Tqj5Q7uSpnsIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});